package ir.moeindeveloper.instaweather.feature.common.util

import androidx.compose.ui.graphics.Color
import ir.moeindeveloper.instaweather.R

enum class WeatherType(val colors: List<Color>,val icon: Int) {
    CLEAR_SKY(
        listOf(
            Color(0xFFffd241),
            Color(0xFFffff00),
            Color(0xFFf3c955)
        ),
        R.drawable.w_ic_clear_sky
    ),
    FEW_CLOUDS(
        listOf(
            Color(0xFF97bcd4),
            Color(0xFFa2bac9),
            Color(0xFF6d99b6)
        ),
        R.drawable.w_ic_few_clouds
    ),
    SCATTERED_CLOUDS(
        listOf(
            Color(0xFFb4b4b4),
            Color(0xFFb7b7b2),
            Color(0xFF94948d)
        ),
        R.drawable.w_ic_scattered_clouds
    ),
    BROKEN_CLOUDS(
        listOf(
            Color(0xFFb9d6df),
            Color(0xFFb4d8e4),
            Color(0xFF78b9ce)
        ),
        R.drawable.w_ic_broken_clouds
    ),
    SHOWER_RAIN(
        listOf(
            Color(0xFF3f6c8f),
            Color(0xFF356d99),
            Color(0xFF325672)
        ),
        R.drawable.w_ic_shower_rain
    ),
    RAIN(
        listOf(
            Color(0xFF5087b2),
            Color(0xFF3f6c8f),
            Color(0xFF4682b4)
        ),
        R.drawable.w_ic_rain
    ),

    THUNDERSTORM(
        listOf(
            Color(0xFF5f646c),
            Color(0xFF5d646e),
            Color(0xFF696969)
        ),
        R.drawable.w_ic_thunderstorm
    ),
    SNOW(
        listOf(
            Color(0xFFffffff),
            Color(0xFFf1eeeb),
            Color(0xFFf5f5f5)
        ),
        R.drawable.w_ic_snow
    ),
    MIST(
        listOf(
            Color(0xFF5e5551),
            Color(0xFF4b4441),
            Color(0xFF4a4442)
        ),
        R.drawable.w_ic_mist
    )
}