name: pullRequest test

on:
  pull_request:
    branches: [ master, develop]
    types: [ assigned, opened, synchronize, reopened ]

jobs:
  build:
    name: Test and build debug APK

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Access WEATHER_API_KEY
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: echo WEATHER_API_KEY=\"$WEATHER_API_KEY\" > ./local.properties
      - name: Build with Gradle after putting API KEY
        run: ./gradlew build
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
      - name: Build with Gradle for debug APK
        run: ./gradlew build
      - name: Build Debug APK
        run: ./gradlew assembleDebug
      - name: Send PR confirmation to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.GROUP_CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          message: |
            Pull request action triggered succussfully
            All tests passed
            Runner OS: ${{ runner.os }}
            Event: ${{ github.event_name }}
            Job ID: ${{ github.job }}
            Triggered by: ${{ github.actor }}
            Branch or TAG: ${{ github.ref }}
            Base ref: ${{ github.base_ref }}
            Head ref: ${{ github.head_ref }}
            Commit SHA: ${{ github.sha }}
            latest commit description: ${{ github.event.head_commit.message }}